version: "3.9"

services:
  rifs:
    image: "rifs:latest"
    build: .
    volumes:
      - ./data:/data
      - ./models:/models
      - ./output:/output
      - ./noise:/noise
    entrypoint: ["rifs", "-help"]